[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "yanjaro-music"
version = "0.1.0"
description = "Minimal Yandex Music desktop client for Manjaro"
requires-python = ">=3.11,<3.15"
dependencies = ["PySide6-Essentials==6.11.2", "python-mpv==1.0.8", "yandex-music==3.2.0"]

[project.scripts]
yanjaro-music = "yanjaro.__main__:main"

[tool.setuptools.package-data]
yanjaro = ["*.qml", "qmldir", "icons/*"]

[tool.setuptools.packages.find]
include = ["yanjaro*"]
